"""Generate an OpenVINS config directory from a rig yaml (single source of truth).

Writes, for a single rig (or, for a composite, per member pod into <out>/<ns>/):
    estimator_config.yaml      ov_msckf parameters (N cameras, stereo pairing, masks)
    kalibr_imucam_chain.yaml   per-camera intrinsics + T_cam_imu from the rig mounts
    kalibr_imu_chain.yaml      IMU noise / rate / topic from the rig
    mask_cam<i>.png            kb4 cameras: image-circle mask (255 = ignore pixel)

Frames. Rig mounts are FLU (rpy 0 = optical axis along +x); OpenVINS reads
Kalibr's T_cam_imu (IMU frame -> camera optical frame, x right / y down /
z forward). The IMU frame is the pod IMU's sensor-local FLU frame (PodIMU
output), so with T_mount_optical = R_MOUNT_OPTICAL:

    T_imu_cam = T_body_imu^-1 . T_body_cam . T_mount_optical
    T_cam_imu = T_imu_cam^-1

VERIFY-IN-SIM: the optical-frame convention (image up = world up for a level
camera). A wrong guess is a 180 deg roll in every extrinsic, which online
extrinsic calibration will not recover from.

Usage:
    python -m bench.gen_openvins_config rigs/pod_3cam_triangle.yaml out_dir/
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

from bench.rigdef import R_MOUNT_OPTICAL, camera_topic, euler_to_R, load_rig, mount_to_T

T_MOUNT_OPTICAL = np.eye(4)
T_MOUNT_OPTICAL[:3, :3] = R_MOUNT_OPTICAL

# Fallbacks when a rig yaml carries no noise values (TUM-VI-class IMU).
DEFAULT_NOISE = {
    "gyro_noise_density": 1.6e-4, "gyro_random_walk": 2.2e-5,
    "accel_noise_density": 2.8e-3, "accel_random_walk": 8.6e-4,
}
# Isaac/Pegasus gravity. VERIFY-IN-SIM against pegasus GRAVITY_VECTOR; a
# 0.003 m/s^2 mismatch is absorbed by the accel bias anyway.
GRAVITY_MAG = 9.81
MASK_RADIUS_FRACTION = 0.98   # shave the extreme rim of the image circle


def cam_T_cam_imu(imu: dict, cam: dict) -> np.ndarray:
    """Kalibr T_cam_imu (IMU -> camera optical) for one camera of a rig."""
    T_body_imu = mount_to_T(imu["body_mount"])
    T_body_cam = mount_to_T(cam["body_mount"]) @ T_MOUNT_OPTICAL
    T_imu_cam = np.linalg.inv(T_body_imu) @ T_body_cam
    return np.linalg.inv(T_imu_cam)


def overlaps(rig: dict, i: int) -> list[int]:
    """Cameras whose boresight lies inside camera i's field of view (and vice versa)."""
    cams = rig["cameras"]

    def boresight(c):
        return euler_to_R(c["body_mount"]["rpy_deg"]) @ np.array([1.0, 0.0, 0.0])

    out = []
    for j, other in enumerate(cams):
        if j == i:
            continue
        cos = float(np.clip(boresight(cams[i]) @ boresight(other), -1.0, 1.0))
        angle = np.degrees(np.arccos(cos))
        half_fov = min(cams[i].get("fov_deg", 190.0), other.get("fov_deg", 190.0)) / 2.0
        if angle < half_fov:
            out.append(j)
    return out


def write_mask(cam: dict, path: Path) -> None:
    """Image-circle mask for an f-theta camera: 255 outside the circle (ignored)."""
    w, h = cam["resolution"]
    intr = cam["intrinsics"]
    theta_max = np.deg2rad(cam.get("fov_deg", 190.0) / 2.0)
    r = intr["fx"] * theta_max * MASK_RADIUS_FRACTION
    ys, xs = np.mgrid[0:h, 0:w]
    outside = (xs + 0.5 - intr["cx"]) ** 2 + (ys + 0.5 - intr["cy"]) ** 2 > r * r
    Image.fromarray(np.where(outside, 255, 0).astype(np.uint8), mode="L").save(path)


def _mat_lines(T: np.ndarray, indent: str = "    ") -> str:
    return "\n".join(f"{indent}- [{', '.join(f'{v:.12g}' for v in row)}]" for row in T)


def _distortion(cam: dict) -> tuple[str, list[float]]:
    intr = cam["intrinsics"]
    if cam["model"] == "kb4":
        return "equidistant", [float(intr.get(k, 0.0)) for k in ("k1", "k2", "k3", "k4")]
    return "radtan", [float(intr.get(k, 0.0)) for k in ("k1", "k2", "p1", "p2")]


def write_imucam_chain(rig: dict, imu: dict, path: Path) -> None:
    blocks = ["%YAML:1.0 # OpenCV yaml — generated by bench/gen_openvins_config.py from "
              f"rig '{rig.get('name', '?')}'; do not edit by hand\n"]
    for i, cam in enumerate(rig["cameras"]):
        model, coeffs = _distortion(cam)
        intr = cam["intrinsics"]
        blocks.append(
            f"cam{i}:\n"
            f"  T_cam_imu: # IMU -> camera optical frame (Kalibr convention)\n"
            f"{_mat_lines(cam_T_cam_imu(imu, cam))}\n"
            f"  cam_overlaps: [{', '.join(str(j) for j in overlaps(rig, i))}]\n"
            f"  camera_model: pinhole\n"
            f"  distortion_coeffs: [{', '.join(f'{c:.12g}' for c in coeffs)}]\n"
            f"  distortion_model: {model}\n"
            f"  intrinsics: [{intr['fx']}, {intr['fy']}, {intr['cx']}, {intr['cy']}]\n"
            f"  resolution: [{cam['resolution'][0]}, {cam['resolution'][1]}]\n"
            f"  rostopic: {camera_topic(rig, cam)}\n"
        )
    path.write_text("\n".join(blocks))


def write_imu_chain(imu: dict, path: Path) -> None:
    noise = {k: float(imu.get(k, v)) for k, v in DEFAULT_NOISE.items()}
    eye = "\n".join(f"    - [ {', '.join('1.0' if r == c else '0.0' for c in range(3))} ]" for r in range(3))
    zero = "\n".join("    - [ 0.0, 0.0, 0.0 ]" for _ in range(3))
    path.write_text(
        "%YAML:1.0 # OpenCV yaml — generated by bench/gen_openvins_config.py\n\n"
        "imu0:\n"
        "  T_i_b:\n"
        "    - [1.0, 0.0, 0.0, 0.0]\n"
        "    - [0.0, 1.0, 0.0, 0.0]\n"
        "    - [0.0, 0.0, 1.0, 0.0]\n"
        "    - [0.0, 0.0, 0.0, 1.0]\n"
        f"  accelerometer_noise_density: {noise['accel_noise_density']}  # [m/s^2/sqrt(Hz)]\n"
        f"  accelerometer_random_walk: {noise['accel_random_walk']}   # [m/s^3/sqrt(Hz)]\n"
        f"  gyroscope_noise_density: {noise['gyro_noise_density']}     # [rad/s/sqrt(Hz)]\n"
        f"  gyroscope_random_walk: {noise['gyro_random_walk']}       # [rad/s^2/sqrt(Hz)]\n"
        f"  rostopic: {imu['topic']}\n"
        "  time_offset: 0.0\n"
        f"  update_rate: {float(imu.get('rate_hz', 400))}\n"
        "  model: \"kalibr\"\n"
        f"  Tw:\n{eye}\n"
        f"  R_IMUtoGYRO:\n{eye}\n"
        f"  Ta:\n{eye}\n"
        f"  R_IMUtoACC:\n{eye}\n"
        f"  Tg:\n{zero}\n"
    )


ESTIMATOR_TEMPLATE = """%YAML:1.0 # OpenCV yaml — generated by bench/gen_openvins_config.py from rig '{rig_name}'

verbosity: "INFO" # ALL, DEBUG, INFO, WARNING, ERROR, SILENT

use_fej: true
integration: "rk4"
# OpenVINS: 2 cameras + use_stereo = stereo tracking; MORE than 2 cameras =
# every camera is tracked mono and the features are fused in the one state
# ("binocular"). (Comments on their own lines: OpenCV's yaml reader keeps
# trailing text in string values.)
use_stereo: {use_stereo}
max_cameras: {max_cameras}

# The whole point of the benchmark: cheap unsynchronized cameras -> keep the
# online spatial-temporal calibration on (sim bags are exactly calibrated and
# synced, skew variants from bench/skew_bag.py are not).
calib_cam_extrinsics: true
calib_cam_intrinsics: true
calib_cam_timeoffset: true
calib_imu_intrinsics: false
calib_imu_g_sensitivity: false

max_clones: 11
max_slam: 50
max_slam_in_update: 25
max_msckf_in_update: 40
dt_slam_delay: 2

gravity_mag: {gravity_mag}

feat_rep_msckf: "GLOBAL_3D"
feat_rep_slam: "ANCHORED_MSCKF_INVERSE_DEPTH"
feat_rep_aruco: "ANCHORED_MSCKF_INVERSE_DEPTH"

try_zupt: false
zupt_chi2_multipler: 0
zupt_max_velocity: 0.1
zupt_noise_multiplier: 50
zupt_max_disparity: 2.0
zupt_only_at_beginning: true

# ==================================================================

# Static initialization on the ground; the takeoff jerk exceeds the threshold.
init_window_time: 1.5
init_imu_thresh: {init_imu_thresh}
init_max_disparity: 15.0
init_max_features: 50

init_dyn_use: false
init_dyn_mle_opt_calib: false
init_dyn_mle_max_iter: 50
init_dyn_mle_max_time: 0.05
init_dyn_mle_max_threads: 6
init_dyn_num_pose: 6
init_dyn_min_deg: 10.0

init_dyn_inflation_ori: 10
init_dyn_inflation_vel: 100
init_dyn_inflation_bg: 10
init_dyn_inflation_ba: 100
init_dyn_min_rec_cond: 1e-20

init_dyn_bias_g: [0.0, 0.0, 0.0]
init_dyn_bias_a: [0.0, 0.0, 0.0]

# ==================================================================

record_timing_information: false
record_timing_filepath: "/tmp/traj_timing.txt"

save_total_state: true
filepath_est: "/out/state_estimate.txt"
filepath_std: "/out/state_std.txt"
filepath_gt: "/out/state_gt.txt"

# ==================================================================

use_klt: true
num_pts: {num_pts}
fast_threshold: 20
grid_x: 5
grid_y: 5
min_px_dist: 15
knn_ratio: 0.65
track_frequency: {track_frequency}
downsample_cameras: false
num_opencv_threads: 4
histogram_method: "HISTOGRAM" # NONE, HISTOGRAM, CLAHE

use_aruco: false
num_aruco: 1024
downsize_aruco: true

# ==================================================================

up_msckf_sigma_px: 1
up_msckf_chi2_multipler: 1
up_slam_sigma_px: 1
up_slam_chi2_multipler: 1
up_aruco_sigma_px: 1
up_aruco_chi2_multipler: 1

# masks (255 = ignore): image circle of the f-theta cameras
use_mask: {use_mask}
{mask_lines}
relative_config_imu: "kalibr_imu_chain.yaml"
relative_config_imucam: "kalibr_imucam_chain.yaml"
"""


def write_estimator_config(rig: dict, path: Path, masks: dict[int, str]) -> None:
    cams = rig["cameras"]
    rate = max(float(c.get("rate_hz", 20)) for c in cams)
    mask_lines = "\n".join(f'mask{i}: "{name}" # relative to this file' for i, name in sorted(masks.items()))
    path.write_text(ESTIMATOR_TEMPLATE.format(
        rig_name=rig.get("name", "?"),
        use_stereo="true" if len(cams) >= 2 and 1 in overlaps(rig, 0) else "false",
        max_cameras=len(cams),
        gravity_mag=GRAVITY_MAG,
        init_imu_thresh=0.45,
        num_pts=200,
        track_frequency=rate + 1.0,
        use_mask="true" if masks else "false",
        mask_lines=(mask_lines + "\n") if masks else "",
    ))


def generate_single(rig: dict, out: Path) -> Path:
    """Write a config dir for a stand-alone rig (or a composite member's `source`)."""
    if rig.get("composite"):
        raise ValueError("generate_single() needs a stand-alone rig; use generate()")
    out.mkdir(parents=True, exist_ok=True)
    imu = rig["imus"][0]
    masks = {}
    for i, cam in enumerate(rig["cameras"]):
        if cam["model"] == "kb4":
            name = f"mask_cam{i}.png"
            write_mask(cam, out / name)
            masks[i] = name
    write_imucam_chain(rig, imu, out / "kalibr_imucam_chain.yaml")
    write_imu_chain(imu, out / "kalibr_imu_chain.yaml")
    write_estimator_config(rig, out / "estimator_config.yaml", masks)
    return out


def generate(rig_path: str, out_dir: str) -> list[Path]:
    """Config dir(s) for a rig yaml: [out] for single rigs, [out/<ns>, ...] for composites."""
    rig = load_rig(rig_path)
    out = Path(out_dir)
    if rig.get("composite"):
        return [generate_single(pod["source"], out / pod["ns"]) for pod in rig["pods"]]
    return [generate_single(rig, out)]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("rig")
    ap.add_argument("out_dir")
    args = ap.parse_args(argv)
    for d in generate(args.rig, args.out_dir):
        print(f"OpenVINS config -> {d}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
